---
title: "Codebook"
author: "Jennifer Beaudry"
date: "20/01/2021"
output: 
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true    
  # pdf_document:
  #   toc: yes
  #   toc_depth: 4
  #   latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually makes debugging easier, and sometimes half a codebook
                # is better than none
  echo = FALSE  # don't show the R code
)
ggplot2::theme_set(ggplot2::theme_bw())
pander::panderOptions("table.split.table", Inf)
```

```{r library}
library(here)
library(tidyverse)
library(codebook)
```


```{r data}

codebook_data <- rio::import(here::here("data", "students_processed.csv"))

# Breadcrumbs: will need to revise this so it imports the cleaned data that I worked with
```

```{r codebook}

codebook_data <- detect_missing(codebook_data,
    only_labelled = TRUE, # only labelled values are autodetected as
                                   # missing
    negative_values_are_missing = FALSE, # negative values are NOT missing values
    ninety_nine_problems = TRUE,   # 99/999 are missing values, if they
                                   # are more than 5 MAD from the median
    )

codebook(codebook_data, 
         metadata_table = TRUE,
         metadata_json = TRUE, 
         survey_overview = FALSE)

# [[breadcrubms: preprocess the data first  & import with the qualtrics reader 
# & then import it into codebook. Use the metadata to change the #labels. 
# Figure out the data labels that we're changing within the raw data itself.]] 
# all done
```


