---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# New Project

<!-- badges: start -->
<!-- badges: end -->

Hi M & M,

I thought I'd try to use Dani Navarro's github template for a new experiment that 
I learned about late last year. Some of these folders won't be necessary for us 
(e.g., experiments, given that we only have one), but she has notes in 
the folders explaining how she uses them, so I think it's helpful to review and 
keep in mind her workflow. I like learning from folks who do these things more than 
I do! So, feel free to play around and read the various readme files. I'll update this as
we go, and I'll add things to the .gitignore as I see fit too (e.g., data -- we'll want
to hide this given that it's a public repo, but we'll need the folder on our computers so
we can run the code). 

jen

This is a template for a new research project. Should contains the following
folders: [analysis](./analysis), [data](./data), [experiments](./experiments),
[other](./other), [preprocessing](./preprocessing). Optionally, it may also 
include a folder `models` containing modelling files, and a `writeup` folder
containing the project writeup. 

If there are other resouces (e.g., OSF folders, Overleaf documents, Google docs)
that are linked to the project, they should be listed in this document.
